id: PA2C709C8
initial_creation_type: input
source_metadata:
  title: Nyangral Nyima Özer Series
  language: bo
  description: 'Texts composed or revealed by the important tertön Nyangral Nyima
    Özer (nyang ral nyi ma ''od zer, 1124–1192):'
  volume:
    edf8b5c99dc344b6902b0c5bdd0e950e:
      title: The Pointing-the-Staff Instruction
      parent: Advice
    8b4aed3a480d43c28ce8c82f78002d53:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Prayers to Guru Rinpoche
    f7b7e883a3904c14a8f0b3d59db76d75:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Prayers to Guru Rinpoche
created_at: '2022-03-01T01:04:34.420032'
last_modified_at: '2022-03-01T01:04:34.420034'
